### ISSUE TITLE
long text to new line ?

### ISSUE THREAD

**Issue by benbiles** [SL-RU/stm32libs#1]
hi , thanks so much for this library!

I think a wrap around text would be a great feature for printing long text strings.
unless its already in there and i missed it ?

**Comment by SL-RU** [comment]
Hello! You are welcome!

I've added that and many more features in the new GUI library: https://github.com/SL-RU/MakiseGUI/tree/dev
It is a bit more complicated, but I'm working on the examples and documentation for now

**Comment by benbiles** [comment]
Amazing !! I'll slowly move over to your new lib , its for an arm stm32f7 based bluetooth audio mixer recorder that has a simple 1" OLED screen that reports some basic info. I wanted to show the current filename playing and they can be long!   👍 👍 👍
