### ISSUE TITLE
How to display Chinese?

### ISSUE THREAD

**Issue by Odeku** [SL-RU/stm32libs#2]
Thank

**Comment by SL-RU** [comment]
That library is old library. There is a new version here: https://github.com/SL-RU/MakiseGUI/tree/dev

It's more complicated, but I've implemented UTF-8 and made tool to generate custom fonts: https://github.com/SL-RU/MakiseGUI/tree/dev/utils/font_creator 

You can generate and use chinese fonts there easily

**Comment by Odeku** [comment]
so cool, but I can't understand it.

Are there any examples?
